CREATE TABLE `tbl_bot_tree` (
  `PKBTREE_NCODIGO` int NOT NULL AUTO_INCREMENT,
  `FKBTREE_NCODIGO` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `BTREE_TIPO_MSG` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `BTREE_OPTION_NUM` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `BTREE_TEXTO` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `BTREE_OPCIONES` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `BTREE_ESTADO` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT 'ACTIVO',
  `TREE_CREATION_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `TREE_MODIFICATION_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`PKBTREE_NCODIGO`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `tbl_chats_management` (
   `PKGES_CODIGO` int NOT NULL AUTO_INCREMENT,
   `FKGES_NUSU_CODIGO` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
   `GES_ESTADO_CASO` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
   `GES_NUMERO_COMUNICA` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
   `GES_NOMBRE_PERFIL` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
   `GES_CTIPO` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
   `GES_CULT_MSGBOT` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
   `GES_CULT_MSGBOT_ARBOL` varchar(70) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
   `GES_CHORA_INICIO_GESTION` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
   `GES_CHORA_FIN_GESTION` timestamp NULL DEFAULT NULL,
   `GES_CFECHA_REGISTRO` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
   `GES_CFECHA_MODIFICACION` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   `GES_CFECHA_PASOASESOR` timestamp NULL DEFAULT NULL,
   `GES_CFECHA_ASIGNACION` timestamp NULL DEFAULT NULL,
   `GES_CDETALLE_ADICIONAL` varchar(250) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
   `GES_CDETALLE_ENCUESTA` varchar(250) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
   `GES_CDETALLE_ADICIONAL2` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
   `GES_CDETALLE_DOCUMENTO` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
   `GES_CDETALLE_CLIENTES` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
   `GES_CDETALLE_ESTADO` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT 'TIPIFICAR',
   `GES_CCORREO` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
   `GES_CESTADO` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
   `GES_NAFK` int DEFAULT '0',
   `GES_CNIVEL` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT 'L1',
   `GES_CANAL` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT 'IN',
   `GES_CLIENTE_NOMBRE` varchar(250) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
   `GES_CLIENTE_EMAIL` varchar(250) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
   `GES_ULTIMO_ENVIADO` timestamp NULL DEFAULT NULL,
   `GES_ULTIMO_RECIBIDO` timestamp NULL DEFAULT NULL,
   `GES_PRIMERO_AGENTE` timestamp NULL DEFAULT NULL,
   `GES_PREGUNTA1` varchar(45) COLLATE utf8mb4_bin DEFAULT NULL,
   `GES_PREGUNTA2` varchar(45) COLLATE utf8mb4_bin DEFAULT NULL,
   `GES_PREGUNTA3` varchar(45) COLLATE utf8mb4_bin DEFAULT NULL,
   PRIMARY KEY (`PKGES_CODIGO`)
 ) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `tbl_client` (
  `PK_CLI_NCODE` int NOT NULL AUTO_INCREMENT,
  `CLI_NAME` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `CLI_IDENTIFICATION_TYPE` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `CLI_IDENTIFICATION_NUMBER` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `CLI_CELLPHONE_NUMBER` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `CLI_EMAIL` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `CLI_REGISTRATION_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `CLI_MODIFICATION_DATE` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `CLI_STATUS` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  PRIMARY KEY (`PK_CLI_NCODE`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `tbl_config_mail` (
  `idtbl_config_mail` int NOT NULL AUTO_INCREMENT,
  `CON_HOST` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT 'NULL',
  `CON_PORT` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT 'NULL',
  `CON_USER` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT 'NULL',
  `CON_PASS` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT 'NULL',
  `CON_ESTADO` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  PRIMARY KEY (`idtbl_config_mail`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `tbl_envio_masivo` (
  `PKENMA_NCODE` int NOT NULL AUTO_INCREMENT,
  `FKUSU_ENMA_CODE` int NOT NULL DEFAULT '0',
  `ENMA_COD_ENVIO` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '0',
  `ENMA_NUMERO_DESTINO` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '0',
  `ENMA_COD_PLANTILLA` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '0',
  `ENMA_COD_LANGUAGE` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `ENMA_ESTADO_ENVIO` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '0',
  `ENMA_NOMBRE_ARCHIVO` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '0',
  `ENMA_CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ENMA_UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `ENMA_DETALLE_ERROR` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `ENMA_NIVEL` varchar(45) COLLATE utf8mb4_bin NOT NULL,
  `ENMA_ESTADO` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT 'Activo',
  PRIMARY KEY (`PKENMA_NCODE`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `tbl_line_profiling` (
  `PKLIPR_NCODE` int NOT NULL AUTO_INCREMENT,
  `LIPR_WHATSAPP_NUM` varchar(45) DEFAULT NULL,
  `LIPR_COUNTRY` varchar(45) DEFAULT NULL,
  `LIPR_ACCOUNT_ID` longtext,
  `LIPR_API_KEY` longtext,
  `LIPR_PROJECT_ROUTE` varchar(255) DEFAULT NULL,
  `LIPR_CREATION_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `LIPR_LAST_MODIFICATION_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `LIPR_URL_BOT` varchar(225) DEFAULT NULL,
  PRIMARY KEY (`PKLIPR_NCODE`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `tbl_messages` (
  `PK_MES_NCODE` int NOT NULL AUTO_INCREMENT,
  `FK_GES_CODIGO` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `MES_ACCOUNT_SID` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `MES_API_VERSION` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `MES_BODY` varchar(4000) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `MES_FROM` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `MES_TO` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `MES_CHANNEL` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `MES_MEDIA_TYPE` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `MES_MEDIA_URL` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `MES_MESSAGE_ID` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `MES_NUM_MEDIA` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `MES_NUM_SEGMENTS` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `MES_PROFILE_NAME` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `MES_REFFAL_NUM_MEDIA` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `MES_SMS_MESSAGE_SID` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `MES_SMS_SID` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `MES_SMS_STATUS` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `MES_WAID` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `MES_CREATION_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `MES_LAST_MODIFICATION_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `MES_DATE_SENT__MESSAGE` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `MES_DATE_CREATED_MESSAGE` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `MES_DATE_UPDATED_MESSAGE` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `MES_DATE_DELIVERED` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `MES_DATE_READ` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `MES_USER` varchar(45) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin DEFAULT NULL,
  `MES_MESSAGE_SHOW` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin DEFAULT NULL,
  PRIMARY KEY (`PK_MES_NCODE`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_bin;

CREATE TABLE `tbl_plantillas` (
  `PKPLA_NCODIGO` int NOT NULL AUTO_INCREMENT,
  `PLA_CNOMBRE` varchar(45) DEFAULT NULL,
  `PLA_CCONTENIDO` mediumtext,
  `PLA_CESTADO` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `PLA_FECHA_REGISTRO` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `PLA_FECHA_MODIFICACION` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`PKPLA_NCODIGO`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `tbl_registro_usuarios` (
  `PKREGU_NCODIGO` int NOT NULL AUTO_INCREMENT,
  `FKREGU_PKUSU_NCODIGO` int DEFAULT NULL,
  `REGU_CUSUARIO` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `REGU_CDOCUMENTO` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `REGU_CAUXILIAR` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `REGU_FECHA_INICIO` timestamp NULL DEFAULT NULL,
  `REGU_FECHA_FIN` timestamp NULL DEFAULT NULL,
  `REGU_TIEMPO` time DEFAULT NULL,
  PRIMARY KEY (`PKREGU_NCODIGO`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `tbl_template` (
  `TEM_NCODIGO` int NOT NULL AUTO_INCREMENT,
  `TEM_TEMPLATE_NAME` varchar(255) DEFAULT NULL,
  `TEM_MESSAGE_TEXT` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `TEM_LENGUAGE` varchar(255) DEFAULT NULL,
  `TEM_STATUS` varchar(50) DEFAULT NULL,
  `TEM_FECHA_REGISTRO` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `TEM_FECHA_MODIFICACION` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `TEM_ESTADO` varchar(50) DEFAULT 'Activo',
  PRIMARY KEY (`TEM_NCODIGO`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `tbl_transfers` (
  `PKTRA_NCODIGO` int NOT NULL AUTO_INCREMENT,
  `FKTRA_NUSU_CODIGO` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `FKTRA_NUSU_TRANSFERIDO` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `FKTRA_NGES_CODIGO` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `TRA_MOTIVO` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `TRA_OBSERVACION` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `TRA_CFECHA_REGISTRO` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `TRA_CFECHA_MODIFICACION` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `TYP_CESTADO` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  PRIMARY KEY (`PKTRA_NCODIGO`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `tbl_typifications` (
  `PKTYP_CODIGO` int NOT NULL AUTO_INCREMENT,
  `FKTYP_NGES_CODIGO` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `FKTYP_NUSU_CODIGO` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `TYP_CRADICADO` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `TYP_CNUMERO` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `TYP_TIPIFICACION` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `TYP_SUBTIPIFICACION` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `TYP_OBSERVACIONES` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `TYP_CFECHA_REGISTRO` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `TYP_CFECHA_MODIFICACION` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `TYP_CESTADO` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  PRIMARY KEY (`PKTYP_CODIGO`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `tbl_usuarios` (
  `PKUSU_NCODIGO` int NOT NULL AUTO_INCREMENT,
  `USU_CNOMBRE` varchar(45) DEFAULT NULL,
  `USU_CDOCUMENTO` varchar(45) DEFAULT NULL,
  `USU_CUSUARIO` varchar(45) DEFAULT NULL,
  `USU_CROL` varchar(45) DEFAULT NULL,
  `USU_CPASSWORD` varchar(45) DEFAULT NULL,
  `USU_TOKEN` varchar(45) DEFAULT NULL,
  `USU_AUTH_TOKEN` varchar(250) DEFAULT NULL,
  `USU_CCAMPANA` varchar(45) DEFAULT NULL,
  `USU_CSKILL` varchar(45) DEFAULT 'L0',
  `USU_CESTADO` varchar(45) DEFAULT 'ACTIVO',
  `USU_CAUXILIAR` varchar(45) DEFAULT NULL,
  `USU_CFECHA_CAMBIO_AUXILIAR` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `USU_CIDIOMA` varchar(3) DEFAULT 'pt',
  `USU_CORREO` varchar(45) DEFAULT NULL,
  `USU_NCHATS` int DEFAULT '0',
  `USU_CESTADO_ANTERIOR` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`PKUSU_NCODIGO`),
  UNIQUE KEY `USU_CUSUARIO_UNIQUE` (`USU_CUSUARIO`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `tbl_rtipificaciones_disponibles` (
   `PKTIP_NCODIGO` int NOT NULL AUTO_INCREMENT,
   `TIP_CNOMBRE_TIPIFICACION` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
   `TIP_CESTADO` varchar(255) COLLATE utf8mb4_bin DEFAULT 'Activo',
   `TIP_CCARGO` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT 'ADMINISTRADOR',
   `TIP_CRESPONSABLE_GESTION` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT 'ANGIE.JARA',
   `TIP_CFECHA_REGISTRO` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
   `TIP_CFECHA_MODIFICACION` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   PRIMARY KEY (`PKTIP_NCODIGO`)
 )

 CREATE TABLE `tbl_opt_select` (
   `PKOP_CODIGO` int NOT NULL AUTO_INCREMENT,
   `OP_CATEGORIA` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
   `OP_OPCION` varchar(250) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
   `OP_ESTADO` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT 'Activo',
   `OP_CREATION_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
   `OP_MODIFICATION_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   PRIMARY KEY (`PKOP_CODIGO`)
 )